version=0.1

[default.global.parameters]
stack_name = "team-elevated-access-notifications"
s3_prefix = "db-aws-iam-identity-center-team"
tags = "doosan:repo=\"https://github.com/DoosanICA/db-aws-iam-identity-center-team\" doosan:owner=\"DI_OPERATIONS\""

profile = "security"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
fail_on_empty_changeset = false
s3_bucket = "dibh-196522590087-us-east-1-cloudformation"
output_template_file="template-packaged.yaml"
role_arn="arn:aws:iam::196522590087:role/CloudFormationDeployer"


[github.global.parameters]
stack_name =  "team-elevated-access-notifications"
s3_prefix = "db-aws-iam-identity-center-team"
tags = "doosan:repo=\"https://github.com/DoosanICA/db-aws-iam-identity-center-team\" doosan:owner=\"DI_OPERATIONS\""

region = "us-east-1"
capabilities = "CAPABILITY_NAMED_IAM"
fail_on_empty_changeset = false
output_template_file="template-packaged.yaml"

[default.deploy.parameters]
template_file = "template-packaged.yaml"

[github.deploy.parameters]
template_file = "template-packaged.yaml"